name: Auto approve

on: 
  pull_request_target:
    paths:
      - "mainnet-canister-revisions.json"

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'cgundy'
    steps:
      - uses: hmarr/auto-approve-action@v4
